<a href="https://colab.research.google.com/github/poojamahajan0712/medium_blog/blob/master/tensors/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Basics

In [ ]:
import torch
import numpy as np

In [ ]:
#rank-2 tensor with zeroes
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#rank-3 tensor , with random numbers
torch.rand(2, 3, 4)

tensor([[[0.2941, 0.4241, 0.6938, 0.4778],
         [0.4725, 0.0579, 0.0536, 0.5375],
         [0.5141, 0.6664, 0.2438, 0.7949]],

        [[0.6658, 0.1356, 0.9488, 0.5355],
         [0.3033, 0.8662, 0.8368, 0.1256],
         [0.0924, 0.7410, 0.3781, 0.6503]]])

In [ ]:
## Understanding size() and shape 
t=torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
print(t)

print("Using size()",t.size())
print("Using shape",t.shape)

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])
Using size() torch.Size([3, 2])
Using shape torch.Size([3, 2])


In [ ]:
## Understanding fill_
t1=torch.tensor([22,33])
print("Tensor ",t1)
t1.fill_(99)
print("Tensor after fill_ operation ",t1)

Tensor  tensor([22, 33])
Tensor after fill_ operation  tensor([99, 99])


In [ ]:
## Tensor/Numpy /Pytorch Interoperability

# Simple Python List
python_list = [3, 22]
# Create a numpy array from python list
numpy_array = np.array(python_list)

# 1. Create a torch Tensor from python list
tensor_from_list = torch.tensor(python_list)

# 2. Create a torch Tensor from Numpy array
tensor_from_array = torch.tensor(numpy_array)

# 3. Another way to create a torch Tensor from Numpy array (share same storage)
tensor_from_array_v2 = torch.from_numpy(numpy_array)

# 4. Convert torch tensor to numpy array
array_from_tensor = tensor_from_array.numpy()

print('List:   ', python_list)
print('Array:  ', numpy_array)
print('Tensor: ', tensor_from_list)
print('Tensor: ', tensor_from_array)
print('Tensor: ', tensor_from_array_v2)
print('Array:  ', array_from_tensor)

List:    [3, 22]
Array:   [ 3 22]
Tensor:  tensor([ 3, 22])
Tensor:  tensor([ 3, 22])
Tensor:  tensor([ 3, 22])
Array:   [ 3 22]


In [ ]:
## DataTypes

tensor = torch.ones(2, 3)
print('Tensor with default type: ', tensor)

tensor = torch.ones(3, 2, dtype=torch.float16)
print('Tensor with 16-bit float: ', tensor)

tensor = torch.ones(2, 3, dtype=torch.bool)
print('Tensor with boolean data: ', tensor)

Tensor with default type:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor with 16-bit float:  tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float16)
Tensor with boolean data:  tensor([[True, True, True],
        [True, True, True]])


In [ ]:
# Indexing  
 
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1][2])
x[0][1] = 8
print(x)

tensor(6)
tensor([[1, 8, 3],
        [4, 5, 6]])


In [ ]:
# View 
x=torch.randn(2,3)
print("Original ",x)
print("View 1 ",x.view(1,6))
print("View 2",x.view(3,-1))

Original  tensor([[-0.1985, -0.1654, -1.9005],
        [ 1.2037,  0.2244, -0.2573]])
View 1  tensor([[-0.1985, -0.1654, -1.9005,  1.2037,  0.2244, -0.2573]])
View 2 tensor([[-0.1985, -0.1654],
        [-1.9005,  1.2037],
        [ 0.2244, -0.2573]])


In [ ]:
w1=torch.ones(2,3)
w1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
## Moving to GPU 
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
print(device)

w2=w1.to(device)
w2

cuda


tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [ ]:
w3=torch.randn(2,3,device=device)
w3

tensor([[-1.0147,  0.7228, -0.8843],
        [ 0.3371,  0.0840, -0.2310]], device='cuda:0')